### ISSUE TITLE
Disable log

### ISSUE THREAD

**Issue by Christophvh** [scoutapp/scout-apm-laravel#23]
Is there a way to disable the log spam? My laravel.log file is filled with Scout messages. I don't mind a log but maybe sent it to a separate file?

**Comment by asgrim** [comment]
The majority of messages should be at the `debug` level, this was intentional to ensure people could configure the logger verbosity in the usual way (if you're not interested in debug, you can turn it off). At the moment, the logger that Scout uses is just the one defined by the `log` service in the container, or where we use DI, the `\Psr\Log\LoggerInterface` service.

We could make this configurable specifically for scout, I'm thinking perhaps:

`scout-logger` which by default would alias to `\Psr\Log\LoggerInterface` but we could add an environment variable to override which service that points to, so you can configure your own logger perhaps?

**Comment by Christophvh** [comment]
Adding an option via the env or config would be the way to go. But I stopped using the product. I spend more time debugging this repo while paying for a service that doesn't log a single thing.

**Comment by asgrim** [comment]
@Christophvh I'm very sorry to hear that. We are working hard on trying to make the Laravel binding as smooth as possible. I'm curious though as to why you're not seeing anything being logged? Do you have `SCOUT_MONITOR=true` in `.env` and your key set in `SCOUT_KEY` etc.?

**Comment by Christophvh** [comment]
Nothing personal, but when there is a big banner with advertising about laravel-integration. A big blogpost with how amazing it is I would assume this package is actually tested, but the first thing I saw when I installed it where issues with this package, my whole application stopped working after installing this. I have to say that the 2 issues were quickly solved, but a whole day of work was still wasted just to get this paid tooling working. 

And yes I had scout-monitor set to true and had spam-logging in my app :
- Scout APM started
- Scout action send 
...

But in the actual scout web application nothing, even after a couple of hours. I switched to another service and it worked instantly without configuration. Maybe in a couple of years when this is grown I will give it a go again.

**Comment by tquiroga** [comment]
Same issue still happening. So many logs, 125 MB of logs across 3 environment, costing me extra on Logging tools... How can we make it stop?

**Comment by asgrim** [comment]
@tquiroga thankfully, this has long since been possible; please set the log level appropriately, for example by setting the `SCOUT_LOG_LEVEL` environment variable. The log levels possible are listed in `Psr\Log\LogLevel`. Thanks!

Scout docs: https://scoutapm.com/docs/php/configuration#log_level

Base library readme also has further details: https://github.com/scoutapp/scout-apm-php#default-log-level

**Comment by cboudreaux** [comment]
> @tquiroga thankfully, this has long since been possible; please set the log level appropriately, for example by setting the `SCOUT_LOG_LEVEL` environment variable. The log levels possible are listed in `Psr\Log\LogLevel`. Thanks!
> 
> Scout docs: https://docs.scoutapm.com/#scout_log_level-1
> 
> Base library readme also has further details: https://github.com/scoutapp/scout-apm-php#default-log-level

This Scout Docs link does not go to any content. It just goes to a landing page.  Can you share the info for disabling the info Log entries?  They are quite excessive.

**Comment by asgrim** [comment]
> This Scout Docs link does not go to any content. It just goes to a landing page. Can you share the info for disabling the info Log entries? They are quite excessive.

The log level can be changed using the `SCOUT_LOG_LEVEL` environment variable, or as previously mentioned, using configuration as described in the link above (https://github.com/scoutapp/scout-apm-php#default-log-level) - hope this helps!

I have updated the location of the new docs - thank you
