### ISSUE TITLE
Configuration conflict with Laravel's Scout

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-laravel#37]
As per [comment](https://github.com/scoutapp/scout-apm-laravel/pull/34#discussion_r358095201):

> scout apm using the name scout.php for configs conflicts with the config file of the first party package Laravel/scout https://github.com/laravel/scout

We can rename the config (and thus, the key used) to `scoutapm` but I'm not sure we can do this in a BC way. Need to check.

**Comment by dlanderson** [comment]
For consistency I'd suggest `scout_apm.php` - we use `scout_apm.yml` in Ruby.

**Comment by cschneid** [comment]
I don't think we worry about BC on this change. It's unlikely anybody has installed the agent since we released it, and used the config file. And the agent should fall back politely onto our suggested ENV configs, without raising exceptions.

We have support@scoutapm.com to help anybody who needs help renaming.

**Comment by asgrim** [comment]
OK; I'll make sure to note it in the `CHANGELOG.md`

**Comment by asgrim** [comment]
Conflict is fixed in `1.2.0` (cc @imhmdb)
