### ISSUE TITLE
Add Laravel Lumen support

### ISSUE THREAD

**Issue by imhmdb** [scoutapp/scout-apm-laravel#48]
scoutAPM doesn't seem to support Laravel Lumen, I opened this issue to request adding support to it.
```
Argument 1 passed to Scoutapm\Laravel\Providers\ScoutApmServiceProvider::Scoutapm\Laravel\Providers\{closure}() must
 implement interface Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application 
given, called in /****/vendor/illuminate/container/Container.php on line 799
```

**Comment by liam-wiltshire** [comment]
I'd +1 this - we (and I suspect many other) use Laravel for our main app and Lumen for various microservices due to the familiarity.

I've fudged together something that 'works' - I've only fixed the features we actually use, so there is a good chance that quite a few things don't work - unfortunately there are quite a few things under the hood that work differently in Lumen, so there was alot of re-working to do!

https://github.com/liam-wiltshire/scout-apm-laravel/tree/lumen-support

**Comment by asgrim** [comment]
Hi Folks - thank you for bringing this to our attention, we'll take a look into what this would involve! :)

**Comment by Casperhr** [comment]
+1 for this

**Comment by Saad-Amjad** [comment]
+1

**Comment by at-thaitran** [comment]
+1

**Comment by emrahsifoglu** [comment]
+1

**Comment by gh-assetplan** [comment]
This would be great.

We have some laravel projects and and a lumen api that powers our mobile apps and most of our 'ajax' needs from our web-based systems. We are adopting ScoutAPM to profile all of our systems, but not having visibility in our Lumen api feels like not seeing the full picture of our performance. I would think that most companies adopting Laravel as their web framework to develop their solutions, sooner or later would need to implement an API using Lumen.

I hope you can add support for this soon 😃  Thanks!!

**Comment by asgrim** [comment]
This is definitely on our radar :)

**Comment by asgrim** [comment]
Please see https://github.com/scoutapp/scout-apm-lumen - any initial feedback is appreciated over there! Thanks folks.

**Comment by gh-assetplan** [comment]
Excellent!! I'll give it a try and let you know :)
