### ISSUE TITLE
Need to support Laravel Version 11

### ISSUE THREAD

**Issue by chiragparmar-kombee** [scoutapp/scout-apm-laravel#96]
Scout does not support the new Laravel 11.x version yet.

https://laravel.com/docs/11.x/upgrade

**Comment by yoeriboven** [comment]
I'm looking at apm so it's really weird l11 isn't supported. It's as if this product is abandoned.

**Comment by asgrim** [comment]
> I'm looking at apm so it's really weird l11 isn't supported. It's as if this product is abandoned.

Laravel 11 support is in the works! Should be released soon 👍 thanks :)

**Comment by manuel-watchenterprise** [comment]
> I'm looking at apm so it's really weird l11 isn't supported. It's as if this product is abandoned.

Exactly. I've already reported them on Discord. Hopefully this "soon" will be soon really.

Our upgrade to L11 is pending just because of this **paid** package, while all of the other packages are ready and compatible already, none of them are paid... Really disappointing, but hopefully it will be done soon.

To me it's very strange as ScoutAPM [was / is] one of the main sponsors of Laravel News and Laracons. 🤷🏼‍♂️

**Comment by asgrim** [comment]
Laravel 11 support has been added in release [2.5.0](https://github.com/scoutapp/scout-apm-laravel/releases/tag/2.5.0). Thanks folks!

**Comment by manuel-watchenterprise** [comment]
> Laravel 11 support has been added in release [2.5.0](https://github.com/scoutapp/scout-apm-laravel/releases/tag/2.5.0). Thanks folks!

Thank you, @asgrim !
